namespace Nuve.Test.Analysis
{
    public class AnalysisGeneralTest
    {
        [Theory]
        [InlineData("bahsedebilirsiniz", 1, new[] {"bahset yAbil Ur sUnUz"})]
        [InlineData("kurda", 2, new[] {"kur DA", "kurt yA"})]
        [InlineData("suyuyla", 1, new[] {"suy sU ylA"})]
        [InlineData("kaçınılmazlaşabilir", 1, new[] {"kaçın Ul mAz lAş yAbil Ur"})]
        [InlineData("iseniz", 1, new[] {"iy ysA nUz"})]
        [InlineData("suyumuz", 1, new[] {"suy UmUz"})]
        [InlineData("meşguldük", 1, new[] {"meşgúl yDU k"})]
        [InlineData("sembolü", 2, new[] {"semból sU", "semból yU"})]
        [InlineData("kıpırdaştığı", 1, new[] {"kıpırdaş DUk sU"})]
        [InlineData("kavrulmak", 1, new[] {"kavur Ul mAk"})]
        [InlineData("saatime", 1, new[] {"saát Um yA"})]
        [InlineData("lağvedebilecekler", 2, new[] {"lağvet yAbil yAcAk lAr", "lağvet yAbil yAcAk lAr"})]
        [InlineData("işaretiymiş", 1, new[] {"işaret sU ymUş"})]
        [InlineData("azaptı", 1, new[] {"azap yDU"})]
        [InlineData("gelecekti", 1, new[] {"gel yAcAk yDU"})]
        [InlineData("yapardı", 1, new[] {"yap Ur yDU"})]
        [InlineData("tuhaftı", 1, new[] {"tuhaf yDU"})]
        [InlineData("arabaydı", 3, new[] {"arap yA yDU", "arap yA yDU", "araba yDU"})]
        [InlineData("kafatasçılardan", 2, new[] {"kafatas CU lAr DAn", "kafatasçı lAr DAn"})]
        [InlineData("sömürüye", 1, new[] {"sömürü yA"})]
        [InlineData("iken", 1, new[] {"iy yken"})]
        [InlineData("kerteye", 1, new[] {"kerte yA"})]
        [InlineData("gibisine", 1, new[] {"gibi sU nA"})]
        [InlineData("Ankara'ya", 1, new[] {"Ankara ' yA"})]
        [InlineData("gelinmek", 1, new[] {"gel Ul mAk"})]
        [InlineData("gidilmek", 1, new[] {"git Ul mAk"})]
        [InlineData("aranmak", 2, new[] {"ara Ul mAk", "aran mAk"})]
        [InlineData("aranılmak", 2, new[] {"ara Ul Ul mAk", "aran Ul mAk"})]
        [InlineData("saklanılmak", 4, new[] {"sak lA Ul Ul mAk", "sak lA Ul Ul mAk", "sakla Ul Ul mAk", "saklan Ul mAk"})]        
        [InlineData("yenmek", 3, new[] {"ye Ul mAk", "yen mAk", "yen mAk"})]
        [InlineData("yenilmek", 3, new[] {"ye Ul Ul mAk", "yen Ul mAk", "yen Ul mAk"})]
        [InlineData("oturulmak", 1, new[] {"otur Ul mAk"})]
        [InlineData("korunmak", 2, new[] {"koru Ul mAk", "korun mAk"})]
        [InlineData("korunulmak", 2, new[] {"koru Ul Ul mAk", "korun Ul mAk"})]
        [InlineData("demek", 1, new[] {"de mAk"})]
        [InlineData("denmek", 1, new[] {"de Ul mAk"})]
        [InlineData("denilmek", 1, new[] {"de Ul Ul mAk"})]
        [InlineData("kavurmak", 1, new[] {"kavur mAk"})]
        [InlineData("savrulmak", 1, new[] {"savur Ul mAk"})]
        [InlineData("savruldum", 1, new[] {"savur Ul DU m"})]
        [InlineData("bununla", 1, new[] {"bun Un ylA"})]
        [InlineData("izninizle", 1, new[] {"izin UnUz ylA"})]
        [InlineData("koynunuza", 1, new[] {"koyun UnUz yA"})]
        [InlineData("çocuksuydu", 1, new[] {"çocuk sU yDU"})]
        [InlineData("ufaktırlar", 1, new[] {"ufak DUr lAr"})]
        [InlineData("kararsızdırlar", 1, new[] {"karar sUz DUr lAr"})]
        [InlineData("tükenmiştirler", 1, new[] {"tüken mUş DUr lAr"})]
        [InlineData("oluyordur", 1, new[] {"ol Uyor DUr"})]
        [InlineData("katlanamam", 2, new[] {"kat lA Ul yAmA m", "kat lA Ul yAmA m"})]
        [InlineData("uğulduyor", 2, new[] {"uğul dA Uyor", "uğul dA Uyor"})]
        [InlineData("yazamam", 1, new[] {"yaz yAmA m"})]
        [InlineData("kalmayalı", 1, new[] {"kal mA yAlI"})]
        [InlineData("meleşiyor", 1, new[] {"meleş Uyor"})]
        [InlineData("şatodakilerin", 2, new[] {"şato DA ki lAr Un", "şato DA ki lAr nUn"})]
        [InlineData("iddianamesinde", 1, new[] {"iddianame sU ndA"})]
        [InlineData("çevresindekilerin", 2, new[] {"çevre sU ndA ki lAr Un", "çevre sU ndA ki lAr nUn"})]
        [InlineData("odadakileri", 2, new[] {"oda DA ki lAr sU", "oda DA ki lAr yU"})]
        [InlineData("evdekiler", 1, new[] {"ev DA ki lAr"})]
        [InlineData("mısınız", 1, new[] {"mı sUnUz"})]
        [InlineData("miydin", 2, new[] {"mi yDU n", "mi yDU n"})]
        [InlineData("miyim", 2, new[] {"mi yUm", "mi yUm"})]
        [InlineData("olsam", 2, new[] {"ol ysA m", "ol sA m"})]
        [InlineData("kalmışlara", 1, new[] {"kal mUş lAr yA"})]
        [InlineData("ezilmişlere", 1, new[] {"ez Ul mUş lAr yA"})]
        [InlineData("fısıldıyordu", 1, new[] {"fısıl dA Uyor yDU"})]
        [InlineData("aşağıdakilerin", 2, new[] {"aşağı DA ki lAr Un", "aşağı DA ki lAr nUn"})]
        [InlineData("şakırdıyor", 1, new[] {"şakır dA Uyor"})]
        [InlineData("pınarlar", 3, new[] {"pınar lA Ur", "pınar lAr", "pınar lAr"})]
        [InlineData("desem", 1, new[] {"de sA m"})]
        [InlineData("yüreciğini", 2, new[] {"yürek CUk sU nU", "yürek CUk Un yU"})]
        [InlineData("parıldıyordu", 1, new[] {"parıl dA Uyor yDU"})]
        [InlineData("terkisinde", 1, new[] {"terki sU ndA"})]
        [InlineData("beğenmişliğiyle", 1, new[] {"beğen mUş lUk sU ylA"})]
        [InlineData("bunları", 1, new[] {"bu lAr yU"})]
        [InlineData("iğrentiye", 1, new[] {"iğrenti yA"})]
        [InlineData("anlayamazdı", 2, new[] {"an lA yAmA Ur yDU", "anla yAmA Ur yDU"})]
        [InlineData("sevdiklerimize", 1, new[] {"sev DUk lAr UmUz yA"})]
        [InlineData("gibiydi", 1, new[] {"gibi yDU"})]
        [InlineData("aldırmazca", 1, new[] {"al DUr mAz CA"})]
        [InlineData("bitirdim", 1, new[] {"bitir DU m"})]
        [InlineData("savunamazdı", 1, new[] {"savun yAmA Ur yDU"})]
        [InlineData("bakabileceği", 1, new[] {"bak yAbil yAcAk sU"})]
        [InlineData("söyleyemezdi", 1, new[] {"söyle yAmA Ur yDU"})]
        [InlineData("gibiydiler", 1, new[] {"gibi yDU lAr"})]
        [InlineData("isteyebileceğini", 2, new[] {"iste yAbil yAcAk sU nU", "iste yAbil yAcAk Un yU"})]
        [InlineData("göremez", 1, new[] {"gör yAmA Ur"})]
        [InlineData("görebileceğini", 2, new[] {"gör yAbil yAcAk sU nU", "gör yAbil yAcAk Un yU"})]
        [InlineData("süzülmüşlüğü", 2, new[] {"süz Ul mUş lUk sU", "süz Ul mUş lUk yU"})]
        [InlineData("edebilmesinin", 1, new[] {"et yAbil mA sU nUn"})]
        [InlineData("anlayabilenlerdendi", 2, new[] {"an lA yAbil yAn lAr DAn yDU", "anla yAbil yAn lAr DAn yDU"})]
        [InlineData("konuşulmamıştır", 1, new[] {"konuş Ul mA mUş DUr"})]
        [InlineData("edemezdi", 1, new[] {"et yAmA Ur yDU"})]
        [InlineData("isteyemezsin", 1, new[] {"iste yAmA Ur sUn"})]
        [InlineData("gördüm", 1, new[] {"gör DU m"})]
        [InlineData("göremeden", 1, new[] {"gör yAmA DAn"})]
        [InlineData("beliriveren", 1, new[] {"belir yUver yAn"})]
        [InlineData("çalmakla", 1, new[] {"çal mAk ylA"})]
        [InlineData("veremeden", 1, new[] {"ver yAmA DAn"})]
        [InlineData("vakti", 2, new[] {"vakit sU", "vakit yU"})]
        [InlineData("yüklendi", 1, new[] {"yük lA Ul DU"})]
        [InlineData("keklemiyorsa", 1, new[] {"kek lA mA Uyor ysA"})]
        [InlineData("okumuyor", 1, new[] {"oku mA Uyor"})]
        [InlineData("oturamıyorum", 1, new[] {"otur yAmA Uyor yUm"})]
        [InlineData("uyumuyorlar", 1, new[] {"uyu mA Uyor lAr"})]
        [InlineData("gideni", 2, new[] {"git yAn sU", "git yAn yU"})]
        [InlineData("olanlar", 1, new[] {"ol yAn lAr"})]
        [InlineData("gelen", 1, new[] {"gel yAn"})]
        [InlineData("mahkemesince", 1, new[] {"mahkeme sU ncA"})]
        [InlineData("diyorum", 1, new[] {"de Uyor yUm"})]
        [InlineData("acemboruları", 2, new[] {"acemboru lAr sU", "acemboru lArI"})]
        [InlineData("acemborusu", 1, new[] {"acemboru sU"})]
        [InlineData("tonlamalar", 1, new[] {"ton lA mA lAr"})]
        [InlineData("atmıyor", 1, new[] {"at mA Uyor"})]
        [InlineData("demiyorum", 1, new[] {"de mA Uyor yUm"})]
        [InlineData("koştum", 1, new[] {"koş DU m"})]
        [InlineData("koşuşturmaca", 1, new[] {"koşuş DUr mAcA"})]
        [InlineData("kadarlardı", 1, new[] {"kadar lAr yDU"})]
        [InlineData("devriyelerde", 1, new[] {"devriye lAr DA"})]
        [InlineData("yanık", 1, new[] {"yanık"})]
        [InlineData("durmamacasına", 1, new[] {"dur mA mA CAsInA"})]
        [InlineData("seferkinden", 1, new[] {"sefer ki ndAn"})]
        [InlineData("düşünsenize", 1, new[] {"düşün sAnIzA"})]
        [InlineData("devrildi", 1, new[] {"devir Ul DU"})]
        [InlineData("mükemmelleştirmekteydi", 1, new[] {"mükemmel lAş DUr mAk DA yDU"})]
        [InlineData("suyunun", 2, new[] {"suy sU nUn", "suy Un nUn"})]
        [InlineData("suyun", 2, new[] {"suy Un", "suy nUn"})]
        [InlineData("bahsederken", 1, new[] {"bahset Ur yken"})]
        [InlineData("bilmeyebilir", 1, new[] {"bil mA yAbil Ur"})]
        [InlineData("kavrulmuş", 2, new[] {"kavur Ul mUş", "kavur Ul mUş"})]
        [InlineData("fısıldaşılan", 1, new[] {"fısıldaş Ul yAn"})]
        [InlineData("opalin", 3, new[] {"opál Un", "opál nUn", "opalin"})]
        [InlineData("isteyecektir", 1, new[] {"iste yAcAk DUr"})]
        [InlineData("istiyorlardır", 1, new[] {"iste Uyor lAr DUr"})]
        [InlineData("dönmeyeyim", 1, new[] {"dön mA yA yUm"})]
        [InlineData("inanılırlığını", 1, new[] {"to do"})]
        [InlineData("kendilerini", 1, new[] {"kendi lArI nU"})]
        [InlineData("kendisininkine", 1, new[] {"kendi sU nUn ki nA"})]
        [InlineData("yiyerek", 1, new[] {"ye yArAk"})]
        [InlineData("diyecekler", 2, new[] {"de yAcAk lAr", "de yAcAk lAr"})]
        [InlineData("banaysa", 2, new[] {"ban yA ysA", "bén yA ysA"})]
        [InlineData("seninkinden", 1, new[] {"sén Un ki ndAn"})]
        [InlineData("tıkıştırılmış", 2, new[] {"tıkış DUr Ul mUş", "tıkış DUr Ul mUş"})]
        [InlineData("karşısındakinin", 1, new[] {"karşı sU ndA ki nUn"})]
        [InlineData("sayenizde", 1, new[] {"saye UnUz DA"})]
        [InlineData("sayesinde", 1, new[] {"saye sU ndA"})]
        [InlineData("beliriverdi", 1, new[] {"belir yUver DU"})]
        [InlineData("kendisiyse", 1, new[] {"kendi sU ysA"})]
        [InlineData("yerleşimimiz", 1, new[] {"to do"})]
        [InlineData("nakde", 1, new[] {"nakit yA"})]
        [InlineData("merhaba", 1, new[] {"merhaba"})]
        [InlineData("acındıracak", 2, new[] {"acı Ul DUr yAcAk", "acı Ul DUr yAcAk"})]
        [InlineData("okurcasına", 1, new[] {"oku Ur CAsInA"})]
        [InlineData("gelesice", 1, new[] {"gel yAsIcA"})]
        [InlineData("inanılmayan", 1, new[] {"inan Ul mA yAn"})]
        [InlineData("geleceğiz", 1, new[] {"gel yAcAk yUz"})]
        [InlineData("istiyordu", 1, new[] {"iste Uyor yDU"})]
        [InlineData("oturuyoruz", 1, new[] {"otur Uyor yUz"})]
        [InlineData("arıyorlarsa", 1, new[] {"ara Uyor lAr ysA"})]
        [InlineData("mükemmeliyete", 1, new[] {"mükemmeliyet yA"})]
        [InlineData("çıkmışlardır", 2, new[] {"çık mUş lAr DUr", "çık mUş lAr DUr"})]
        [InlineData("burada", 1, new[] {"bura DA"})]
        [InlineData("ulaştıktan", 1, new[] {"ulaş DUk DAn"})]
        [InlineData("hayli", 1, new[] {"hayli"})]
        [InlineData("çözemediği", 1, new[] {"çöz yAmA DUk sU"})]
        [InlineData("okundukları", 2, new[] {"oku Ul DUk lAr sU", "oku Ul DUk lArI"})]
        [InlineData("anlaşılabilir", 1, new[] {"an lAş Ul yAbil Ur"})]
        [InlineData("varılabilir", 1, new[] {"var Ul yAbil Ur"})]
        [InlineData("hiçbir", 1, new[] {"hiçbir"})]
        [InlineData("görülmez", 2, new[] {"gör Ul mA Ur", "gör Ul mAz"})]
        [InlineData("görünen", 1, new[] {"görün yAn"})]
        [InlineData("yaklaştıran", 2, new[] {"yak lAş DUr yAn", "yaklaş DUr yAn"})]
        [InlineData("sanatkaranedir", 1, new[] {"sanatkârane DUr"})]
        [InlineData("kutbuna", 2, new[] {"kutup sU nA", "kutup Un yA"})]
        [InlineData("görünüşüne", 2, new[] {"görün yUş sU nA", "görün yUş Un yA"})]
        [InlineData("bakmaz", 2, new[] {"bak mA Ur", "bak mAz"})]
        [InlineData("iner", 1, new[] {"in Ur"})]
        [InlineData("tecessüsü", 2, new[] {"tecessüs sU", "tecessüs yU"})]
        [InlineData("ayrılır", 1, new[] {"ayrıl Ur"})]
        [InlineData("eden", 1, new[] {"et yAn"})]
        [InlineData("olmalıdır", 2, new[] {"ol mA lU DUr", "ol mAlI DUr"})]
        [InlineData("görüldüğü", 1, new[] {"gör Ul DUk sU"})]
        [InlineData("hissederiz", 1, new[] {"hisset Ur yUz"})]
        [InlineData("bulacaklardır", 2, new[] {"bul yAcAk lAr DUr", "bul yAcAk lAr DUr"})]
        [InlineData("vasıtasıdır", 1, new[] {"vasıta sU DUr"})]
        [InlineData("katılmasını", 1, new[] {"kat Ul mA sU nU"})]
        [InlineData("etmesindendir", 1, new[] {"et mA sU ndAn DUr"})]
        [InlineData("yemekhanesinde", 1, new[] {"yemekhane sU ndA"})]
        [InlineData("aktarıldı", 1, new[] {"aktar Ul DU"})]
        [InlineData("karlarla", 2, new[] {"kar lAr ylA", "kâr lAr ylA"})]
        [InlineData("konuştuğu", 1, new[] {"konuş DUk sU"})]
        [InlineData("duyduğu", 1, new[] {"duy DUk sU"})]
        [InlineData("yazdığı", 1, new[] {"yaz DUk sU"})]
        [InlineData("çevrecilikle", 2, new[] {"çevre CU lUk ylA", "çevre CU lUk lA"})]
        [InlineData("olan", 1, new[] {"ol yAn"})]
        [InlineData("verilen", 2, new[] {"ver Ul yAn", "veri lA Ul"})]
        [InlineData("gösterileceği", 1, new[] {"göster Ul yAcAk sU"})]
        [InlineData("yaşındayken", 4, new[] {"yaş sU ndA yken", "yaş Un DA yken", "yaş sU ndA yken", "yaş Un DA yken"})]
        [InlineData("ailesinin", 1, new[] {"aile sU nUn"})]
        [InlineData("odasının", 1, new[] {"oda sU nUn"})]
        [InlineData("yatan", 1, new[] {"yat yAn"})]
        [InlineData("karanlığını", 2, new[] {"karanlık sU nU", "karanlık Un yU"})]
        [InlineData("sanırım", 1, new[] {"san Ur yUm"})]
        [InlineData("tuttuğu", 1, new[] {"tut DUk sU"})]
        [InlineData("ittiğinde", 2, new[] {"it DUk sU ndA", "it DUk Un DA"})]
        [InlineData("geleceğimizden", 1, new[] {"gel yAcAk UmUz DAn"})]
        [InlineData("saatte", 1, new[] {"saát DA"})]
        [InlineData("affa", 1, new[] {"af yA"})]
        [InlineData("burnumdan", 1, new[] {"burun Um DAn"})]
        [InlineData("ikincilerse", 3, new[] {"iki UncU lA Ur ysA", "iki UncU lAr ysA", "iki UncU lAr ysA"})]
        [InlineData("kitaba", 1, new[] {"kitap yA"})]
        [InlineData("cengi", 2, new[] {"cenk sU", "cenk yU"})]
        [InlineData("elmalardandır", 1, new[] {"elma lAr DAn DUr"})]
        [InlineData("aynasızlar", 3, new[] {"ayna sUz lA Ur", "ayna sUz lAr", "ayna sUz lAr"})]
        [InlineData("zemberekçilik", 1, new[] {"zemberek CU lUk"})]
        [InlineData("vebali", 2, new[] {"vebál sU", "vebál yU"})]
        [InlineData("yukarıdakilerin", 2, new[] {"yukarı DA ki lAr Un", "yukarı DA ki lAr nUn"})]
        public void HepsiDogruTest(string token, int count, string[] analyses)
        {
            Tester.TestAnalyses(token, count, analyses);
        }

        [Theory]
        [InlineData("gelilmek")]
        [InlineData("aralacak")]
        [InlineData("saklanınmak")]
        [InlineData("yeil")]
        [InlineData("yeninmek")]
        [InlineData("dimekle")]
        [InlineData("deninmek")]
        [InlineData("kavurulmak")]
        [InlineData("kavrunmak")]
        [InlineData("savuruldum")]
        [InlineData("yeyerek")]
        [InlineData("deyeceklerim")]
        [InlineData("saatım")]
        [InlineData("burunuma")]
        [InlineData("kitapa")]
        [InlineData("nerdesin")]
        [InlineData("cenki")]
        [InlineData("arayorlar")]
        [InlineData("azapdı")]
        [InlineData("gelecekdi")]
        [InlineData("arabadı")]
        [InlineData("tuhafdı")]
        [InlineData("kendilik")]
        [InlineData("kendiliğim")]
        public void HepsiYanlısTest(string token)
        {
            Tester.HasNoAnalysis(token);
        }

        [Theory]
        [InlineData("yaptırıveremedim")]
        [InlineData("arttıracağını")]
        [InlineData("nasılsın")]
        [InlineData("Keloğlan'a")]
        [InlineData("hepiniz")]
        [InlineData("hepimiz")]
        [InlineData("önceden")]
        [InlineData("dolayısıyla")]
        [InlineData("a.ş.")]
        [InlineData("km")]
        [InlineData("hepimizin")]
        [InlineData("böylelikle")]
        [InlineData("böylesi")]
        [InlineData("usulü")]
        [InlineData("kadarlık")]
        [InlineData("kadardır")]
        [InlineData("kadarsın")]
        [InlineData("öyleyim")]
        [InlineData("şunlardı")]
        public void ValidWordsTest(string token)
        {
            Tester.HasAnalysis(token);
        }
    }
}