using NUnit.Framework;

namespace Nuve.Test.Analysis
{
    [TestFixture]
    internal class AnalysisGeneralTest
    {
        [TestCase("bahsedebilirsiniz", 1, new[] {"bahset yAbil Ur sUnUz"})]
        [TestCase("kurda", 2, new[] {"kur DA", "kurt yA"})]
        [TestCase("suyuyla", 1, new[] {"suy sU ylA"})]
        [TestCase("kaçınılmazlaşabilir", 1, new[] {"kaçın Ul mAz lAş yAbil Ur"})]
        [TestCase("iseniz", 1, new[] {"iy ysA nUz"})]
        [TestCase("suyumuz", 1, new[] {"suy UmUz"})]
        [TestCase("meşguldük", 1, new[] {"meşgúl yDU k"})]
        [TestCase("sembolü", 2, new[] {"semból sU", "semból yU"})]
        [TestCase("kıpırdaştığı", 1, new[] {"kıpırdaş DUk sU"})]
        [TestCase("kavrulmak", 1, new[] {"kavur Ul mAk"})]
        [TestCase("saatime", 1, new[] {"saát Um yA"})]
        [TestCase("lağvedebilecekler", 2, new[] {"lağvet yAbil yAcAk lAr", "lağvet yAbil yAcAk lAr"})]
        [TestCase("işaretiymiş", 1, new[] {"işaret sU ymUş"})]
        [TestCase("azaptı", 1, new[] {"azap yDU"})]
        [TestCase("gelecekti", 1, new[] {"gel yAcAk yDU"})]
        [TestCase("yapardı", 1, new[] {"yap Ur yDU"})]
        [TestCase("tuhaftı", 1, new[] {"tuhaf yDU"})]
        [TestCase("arabaydı", 3, new[] {"arap yA yDU", "arap yA yDU", "araba yDU"})]
        [TestCase("kafatasçılardan", 2, new[] {"kafatas CU lAr DAn", "kafatasçı lAr DAn"})]
        [TestCase("sömürüye", 1, new[] {"sömürü yA"})]
        [TestCase("iken", 1, new[] {"iy yken"})]
        [TestCase("kerteye", 1, new[] {"kerte yA"})]
        [TestCase("gibisine", 1, new[] {"gibi sU nA"})]
        [TestCase("Ankara'ya", 1, new[] {"Ankara ' yA"})]
        [TestCase("gelinmek", 1, new[] {"gel Ul mAk"})]
        [TestCase("gidilmek", 1, new[] {"git Ul mAk"})]
        [TestCase("aranmak", 2, new[] {"ara Ul mAk", "aran mAk"})]
        [TestCase("aranılmak", 2, new[] {"ara Ul Ul mAk", "aran Ul mAk"})]
        [TestCase("saklanılmak", 4, new[] {"sak lA Ul Ul mAk", "sak lA Ul Ul mAk", "sakla Ul Ul mAk", "saklan Ul mAk"})]
        [TestCase("aranmak", 2, new[] {"ara Ul mAk", "aran mAk"})]
        [TestCase("yenmek", 3, new[] {"ye Ul mAk", "yen mAk", "yen mAk"})]
        [TestCase("yenilmek", 3, new[] {"ye Ul Ul mAk", "yen Ul mAk", "yen Ul mAk"})]
        [TestCase("oturulmak", 1, new[] {"otur Ul mAk"})]
        [TestCase("korunmak", 2, new[] {"koru Ul mAk", "korun mAk"})]
        [TestCase("korunulmak", 2, new[] {"koru Ul Ul mAk", "korun Ul mAk"})]
        [TestCase("demek", 1, new[] {"de mAk"})]
        [TestCase("denmek", 1, new[] {"de Ul mAk"})]
        [TestCase("denilmek", 1, new[] {"de Ul Ul mAk"})]
        [TestCase("kavurmak", 1, new[] {"kavur mAk"})]
        [TestCase("savrulmak", 1, new[] {"savur Ul mAk"})]
        [TestCase("savruldum", 1, new[] {"savur Ul DU m"})]
        [TestCase("bununla", 1, new[] {"bun Un ylA"})]
        [TestCase("izninizle", 1, new[] {"izin UnUz ylA"})]
        [TestCase("koynunuza", 1, new[] {"koyun UnUz yA"})]
        [TestCase("çocuksuydu", 1, new[] {"çocuk sU yDU"})]
        [TestCase("ufaktırlar", 1, new[] {"ufak DUr lAr"})]
        [TestCase("kararsızdırlar", 1, new[] {"karar sUz DUr lAr"})]
        [TestCase("tükenmiştirler", 1, new[] {"tüken mUş DUr lAr"})]
        [TestCase("oluyordur", 1, new[] {"ol Uyor DUr"})]
        [TestCase("katlanamam", 2, new[] {"kat lA Ul yAmA m", "kat lA Ul yAmA m"})]
        [TestCase("yazamam", 1, new[] {"yaz yAmA m"})]
        [TestCase("uğulduyor", 2, new[] {"uğul dA Uyor", "uğul dA Uyor"})]
        [TestCase("yazamam", 1, new[] {"yaz yAmA m"})]
        [TestCase("kalmayalı", 1, new[] {"kal mA yAlI"})]
        [TestCase("meleşiyor", 1, new[] {"meleş Uyor"})]
        [TestCase("şatodakilerin", 2, new[] {"şato DA ki lAr Un", "şato DA ki lAr nUn"})]
        [TestCase("iddianamesinde", 1, new[] {"iddianame sU ndA"})]
        [TestCase("çevresindekilerin", 2, new[] {"çevre sU ndA ki lAr Un", "çevre sU ndA ki lAr nUn"})]
        [TestCase("odadakileri", 2, new[] {"oda DA ki lAr sU", "oda DA ki lAr yU"})]
        [TestCase("evdekiler", 1, new[] {"ev DA ki lAr"})]
        [TestCase("mısınız", 1, new[] {"mı sUnUz"})]
        [TestCase("miydin", 2, new[] {"mi yDU n", "mi yDU n"})]
        [TestCase("miyim", 2, new[] {"mi yUm", "mi yUm"})]
        [TestCase("olsam", 2, new[] {"ol ysA m", "ol sA m"})]
        [TestCase("kalmışlara", 1, new[] {"kal mUş lAr yA"})]
        [TestCase("ezilmişlere", 1, new[] {"ez Ul mUş lAr yA"})]
        [TestCase("fısıldıyordu", 1, new[] {"fısıl dA Uyor yDU"})]
        [TestCase("aşağıdakilerin", 2, new[] {"aşağı DA ki lAr Un", "aşağı DA ki lAr nUn"})]
        [TestCase("şakırdıyor", 1, new[] {"şakır dA Uyor"})]
        [TestCase("pınarlar", 3, new[] {"pınar lA Ur", "pınar lAr", "pınar lAr"})]
        [TestCase("desem", 1, new[] {"de sA m"})]
        [TestCase("yüreciğini", 2, new[] {"yürek CUk sU nU", "yürek CUk Un yU"})]
        [TestCase("parıldıyordu", 1, new[] {"parıl dA Uyor yDU"})]
        [TestCase("terkisinde", 1, new[] {"terki sU ndA"})]
        [TestCase("beğenmişliğiyle", 1, new[] {"beğen mUş lUk sU ylA"})]
        [TestCase("bunları", 1, new[] {"bu lAr yU"})]
        [TestCase("gibiydi", 1, new[] {"gibi yDU"})]
        [TestCase("iğrentiye", 1, new[] {"iğrenti yA"})]
        [TestCase("anlayamazdı", 2, new[] {"an lA yAmA Ur yDU", "anla yAmA Ur yDU"})]
        [TestCase("sevdiklerimize", 1, new[] {"sev DUk lAr UmUz yA"})]
        [TestCase("gibiydi", 1, new[] {"gibi yDU"})]
        [TestCase("aldırmazca", 1, new[] {"al DUr mAz CA"})]
        [TestCase("bitirdim", 1, new[] {"bitir DU m"})]
        [TestCase("savunamazdı", 1, new[] {"savun yAmA Ur yDU"})]
        [TestCase("bakabileceği", 1, new[] {"bak yAbil yAcAk sU"})]
        [TestCase("söyleyemezdi", 1, new[] {"söyle yAmA Ur yDU"})]
        [TestCase("gibiydiler", 1, new[] {"gibi yDU lAr"})]
        [TestCase("isteyebileceğini", 2, new[] {"iste yAbil yAcAk sU nU", "iste yAbil yAcAk Un yU"})]
        [TestCase("göremez", 1, new[] {"gör yAmA Ur"})]
        [TestCase("görebileceğini", 2, new[] {"gör yAbil yAcAk sU nU", "gör yAbil yAcAk Un yU"})]
        [TestCase("süzülmüşlüğü", 2, new[] {"süz Ul mUş lUk sU", "süz Ul mUş lUk yU"})]
        [TestCase("edebilmesinin", 1, new[] {"et yAbil mA sU nUn"})]
        [TestCase("anlayabilenlerdendi", 2, new[] {"an lA yAbil yAn lAr DAn yDU", "anla yAbil yAn lAr DAn yDU"})]
        [TestCase("konuşulmamıştır", 1, new[] {"konuş Ul mA mUş DUr"})]
        [TestCase("edemezdi", 1, new[] {"et yAmA Ur yDU"})]
        [TestCase("isteyemezsin", 1, new[] {"iste yAmA Ur sUn"})]
        [TestCase("gördüm", 1, new[] {"gör DU m"})]
        [TestCase("göremeden", 1, new[] {"gör yAmA DAn"})]
        [TestCase("beliriveren", 1, new[] {"belir yUver yAn"})]
        [TestCase("çalmakla", 1, new[] {"çal mAk ylA"})]
        [TestCase("veremeden", 1, new[] {"ver yAmA DAn"})]
        [TestCase("vakti", 2, new[] {"vakit sU", "vakit yU"})]
        [TestCase("yüklendi", 1, new[] {"yük lA Ul DU"})]
        [TestCase("keklemiyorsa", 1, new[] {"kek lA mA Uyor ysA"})]
        [TestCase("okumuyor", 1, new[] {"oku mA Uyor"})]
        [TestCase("oturamıyorum", 1, new[] {"otur yAmA Uyor yUm"})]
        [TestCase("uyumuyorlar", 1, new[] {"uyu mA Uyor lAr"})]
        [TestCase("gideni", 2, new[] {"git yAn sU", "git yAn yU"})]
        [TestCase("olanlar", 1, new[] {"ol yAn lAr"})]
        [TestCase("gelen", 1, new[] {"gel yAn"})]
        [TestCase("mahkemesince", 1, new[] {"mahkeme sU ncA"})]
        [TestCase("diyorum", 1, new[] {"de Uyor yUm"})]
        [TestCase("acemboruları", 2, new[] {"acemboru lAr sU", "acemboru lArI"})]
        [TestCase("acemborusu", 1, new[] {"acemboru sU"})]
        [TestCase("tonlamalar", 1, new[] {"ton lA mA lAr"})]
        [TestCase("atmıyor", 1, new[] {"at mA Uyor"})]
        [TestCase("demiyorum", 1, new[] {"de mA Uyor yUm"})]
        [TestCase("koştum", 1, new[] {"koş DU m"})]
        [TestCase("koşuşturmaca", 1, new[] {"koşuş DUr mAcA"})]
        [TestCase("kadarlardı", 1, new[] {"kadar lAr yDU"})]
        [TestCase("devriyelerde", 1, new[] {"devriye lAr DA"})]
        [TestCase("yanık", 1, new[] {"yanık"})]
        [TestCase("durmamacasına", 1, new[] {"dur mA mA CAsInA"})]
        [TestCase("seferkinden", 1, new[] {"sefer ki ndAn"})]
        [TestCase("düşünsenize", 1, new[] {"düşün sAnIzA"})]
        [TestCase("devrildi", 1, new[] {"devir Ul DU"})]
        [TestCase("mükemmelleştirmekteydi", 1, new[] {"mükemmel lAş DUr mAk DA yDU"})]
        [TestCase("suyunun", 2, new[] {"suy sU nUn", "suy Un nUn"})]
        [TestCase("suyun", 2, new[] {"suy Un", "suy nUn"})]
        [TestCase("bahsederken", 1, new[] {"bahset Ur yken"})]
        [TestCase("bilmeyebilir", 1, new[] {"bil mA yAbil Ur"})]
        [TestCase("kavrulmuş", 2, new[] {"kavur Ul mUş", "kavur Ul mUş"})]
        [TestCase("fısıldaşılan", 1, new[] {"fısıldaş Ul yAn"})]
        [TestCase("opalin", 3, new[] {"opál Un", "opál nUn", "opalin"})]
        [TestCase("isteyecektir", 1, new[] {"iste yAcAk DUr"})]
        [TestCase("istiyorlardır", 1, new[] {"iste Uyor lAr DUr"})]
        [TestCase("dönmeyeyim", 1, new[] {"dön mA yA yUm"})]
        [TestCase("inanılırlığını", 1, new[] {"to do"})]
        [TestCase("kendilerini", 1, new[] {"kendi lArI nU"})]
        [TestCase("kendisininkine", 1, new[] {"kendi sU nUn ki nA"})]
        [TestCase("yiyerek", 1, new[] {"ye yArAk"})]
        [TestCase("diyecekler", 2, new[] {"de yAcAk lAr", "de yAcAk lAr"})]
        [TestCase("banaysa", 2, new[] {"ban yA ysA", "bén yA ysA"})]
        [TestCase("seninkinden", 1, new[] {"sén Un ki ndAn"})]
        [TestCase("tıkıştırılmış", 2, new[] {"tıkış DUr Ul mUş", "tıkış DUr Ul mUş"})]
        [TestCase("karşısındakinin", 1, new[] {"karşı sU ndA ki nUn"})]
        [TestCase("sayenizde", 1, new[] {"saye UnUz DA"})]
        [TestCase("sayesinde", 1, new[] {"saye sU ndA"})]
        [TestCase("beliriverdi", 1, new[] {"belir yUver DU"})]
        [TestCase("kendisiyse", 1, new[] {"kendi sU ysA"})]
        [TestCase("yerleşimimiz", 1, new[] {"to do"})]
        [TestCase("nakde", 1, new[] {"nakit yA"})]
        [TestCase("merhaba", 1, new[] {"merhaba"})]
        [TestCase("acındıracak", 2, new[] {"acı Ul DUr yAcAk", "acı Ul DUr yAcAk"})]
        [TestCase("okurcasına", 1, new[] {"oku Ur CAsInA"})]
        [TestCase("gelesice", 1, new[] {"gel yAsIcA"})]
        [TestCase("inanılmayan", 1, new[] {"inan Ul mA yAn"})]
        [TestCase("geleceğiz", 1, new[] {"gel yAcAk yUz"})]
        [TestCase("istiyordu", 1, new[] {"iste Uyor yDU"})]
        [TestCase("oturuyoruz", 1, new[] {"otur Uyor yUz"})]
        [TestCase("arıyorlarsa", 1, new[] {"ara Uyor lAr ysA"})]
        [TestCase("mükemmeliyete", 1, new[] {"mükemmeliyet yA"})]
        [TestCase("çıkmışlardır", 2, new[] {"çık mUş lAr DUr", "çık mUş lAr DUr"})]
        [TestCase("burada", 1, new[] {"bura DA"})]
        [TestCase("ulaştıktan", 1, new[] {"ulaş DUk DAn"})]
        [TestCase("hayli", 1, new[] {"hayli"})]
        [TestCase("çözemediği", 1, new[] {"çöz yAmA DUk sU"})]
        [TestCase("okundukları", 2, new[] {"oku Ul DUk lAr sU", "oku Ul DUk lArI"})]
        [TestCase("anlaşılabilir", 1, new[] {"an lAş Ul yAbil Ur"})]
        [TestCase("varılabilir", 1, new[] {"var Ul yAbil Ur"})]
        [TestCase("hiçbir", 1, new[] {"hiçbir"})]
        [TestCase("görülmez", 2, new[] {"gör Ul mA Ur", "gör Ul mAz"})]
        [TestCase("görünen", 1, new[] {"görün yAn"})]
        [TestCase("yaklaştıran", 2, new[] {"yak lAş DUr yAn", "yaklaş DUr yAn"})]
        [TestCase("sanatkaranedir", 1, new[] {"sanatkârane DUr"})]
        [TestCase("kutbuna", 2, new[] {"kutup sU nA", "kutup Un yA"})]
        [TestCase("görünüşüne", 2, new[] {"görün yUş sU nA", "görün yUş Un yA"})]
        [TestCase("bakmaz", 2, new[] {"bak mA Ur", "bak mAz"})]
        [TestCase("iner", 1, new[] {"in Ur"})]
        [TestCase("tecessüsü", 2, new[] {"tecessüs sU", "tecessüs yU"})]
        [TestCase("ayrılır", 1, new[] {"ayrıl Ur"})]
        [TestCase("eden", 1, new[] {"et yAn"})]
        [TestCase("olmalıdır", 2, new[] {"ol mA lU DUr", "ol mAlI DUr"})]
        [TestCase("görüldüğü", 1, new[] {"gör Ul DUk sU"})]
        [TestCase("hissederiz", 1, new[] {"hisset Ur yUz"})]
        [TestCase("bulacaklardır", 2, new[] {"bul yAcAk lAr DUr", "bul yAcAk lAr DUr"})]
        [TestCase("vasıtasıdır", 1, new[] {"vasıta sU DUr"})]
        [TestCase("katılmasını", 1, new[] {"kat Ul mA sU nU"})]
        [TestCase("etmesindendir", 1, new[] {"et mA sU ndAn DUr"})]
        [TestCase("yemekhanesinde", 1, new[] {"yemekhane sU ndA"})]
        [TestCase("aktarıldı", 1, new[] {"aktar Ul DU"})]
        [TestCase("karlarla", 2, new[] {"kar lAr ylA", "kâr lAr ylA"})]
        [TestCase("konuştuğu", 1, new[] {"konuş DUk sU"})]
        [TestCase("duyduğu", 1, new[] {"duy DUk sU"})]
        [TestCase("yazdığı", 1, new[] {"yaz DUk sU"})]
        [TestCase("çevrecilikle", 2, new[] {"çevre CU lUk ylA", "çevre CU lUk lA"})]
        [TestCase("olan", 1, new[] {"ol yAn"})]
        [TestCase("verilen", 2, new[] {"ver Ul yAn", "veri lA Ul"})]
        [TestCase("gösterileceği", 1, new[] {"göster Ul yAcAk sU"})]
        [TestCase("yaşındayken", 4, new[] {"yaş sU ndA yken", "yaş Un DA yken", "yaş sU ndA yken", "yaş Un DA yken"})]
        [TestCase("ailesinin", 1, new[] {"aile sU nUn"})]
        [TestCase("odasının", 1, new[] {"oda sU nUn"})]
        [TestCase("yatan", 1, new[] {"yat yAn"})]
        [TestCase("karanlığını", 2, new[] {"karanlık sU nU", "karanlık Un yU"})]
        [TestCase("sanırım", 1, new[] {"san Ur yUm"})]
        [TestCase("tuttuğu", 1, new[] {"tut DUk sU"})]
        [TestCase("ittiğinde", 2, new[] {"it DUk sU ndA", "it DUk Un DA"})]
        [TestCase("mısınız", 1, new[] {"mı sUnUz"})]
        [TestCase("geleceğimizden", 1, new[] {"gel yAcAk UmUz DAn"})]
        [TestCase("saatte", 1, new[] {"saát DA"})]
        [TestCase("affa", 1, new[] {"af yA"})]
        [TestCase("burnumdan", 1, new[] {"burun Um DAn"})]
        [TestCase("ikincilerse", 3, new[] {"iki UncU lA Ur ysA", "iki UncU lAr ysA", "iki UncU lAr ysA"})]
        [TestCase("kitaba", 1, new[] {"kitap yA"})]
        [TestCase("cengi", 2, new[] {"cenk sU", "cenk yU"})]
        [TestCase("elmalardandır", 1, new[] {"elma lAr DAn DUr"})]
        [TestCase("aynasızlar", 3, new[] {"ayna sUz lA Ur", "ayna sUz lAr", "ayna sUz lAr"})]
        [TestCase("zemberekçilik", 1, new[] {"zemberek CU lUk"})]
        [TestCase("vebali", 2, new[] {"vebál sU", "vebál yU"})]
        [TestCase("yukarıdakilerin", 2, new[] {"yukarı DA ki lAr Un", "yukarı DA ki lAr nUn"})]
        public void HepsiDogruTest(string token, int count, string[] analyses)
        {
            Tester.TestAnalyses(token, count, analyses);
        }

        [TestCase("gelilmek")]
        [TestCase("aralacak")]
        [TestCase("saklanınmak")]
        [TestCase("yeil")]
        [TestCase("yeninmek")]
        [TestCase("dimekle")]
        [TestCase("deninmek")]
        [TestCase("kavurulmak")]
        [TestCase("kavrunmak")]
        [TestCase("savuruldum")]
        [TestCase("yeyerek")]
        [TestCase("deyeceklerim")]
        [TestCase("saatım")]
        [TestCase("burunuma")]
        [TestCase("kitapa")]
        [TestCase("nerdesin")]
        [TestCase("cenki")]
        [TestCase("arayorlar")]
        [TestCase("azapdı")]
        [TestCase("gelecekdi")]
        [TestCase("arabadı")]
        [TestCase("tuhafdı")]
        public void HepsiYanlısTest(string token)
        {
            Tester.HasNoAnalysis(token);
        }
    }
}