using System;
using System.Collections.Generic;
using System.Linq;
using Nuve.Orthographic;
using Nuve.Tokenizers;

namespace Nuve.Sentence
{
    internal class TokenBasedSentenceSegmenter : SentenceSegmenter
    {
        private static readonly string[] Closing = {"\"", "\'", ")"};
        private static readonly string[] Opening = {"\"", "\'", "("};
        private static readonly string[] EosCandidateTokens = {".", "?", "!", "...", "\"", "]"};

        /// <summary>
        ///     todo: bu liste Türkçe dilinden alınmalı
        /// </summary>
        private readonly string[] _abvvs =
        {
            "age.",
            "agm.",
            "agy.",
            "Alb.",
            "Alm.",
            "anat.",
            "ant.",
            "Apt.",
            "Ar.",
            "Arş.",
            "Gör.",
            "ark.",
            "As.",
            "Asb.",
            "As.",
            "İz.",
            "astr.",
            "astrol.",
            "Atğm.",
            "atm.",
            "Av.",
            "bağ.",
            "Bçvş.",
            "bitb.",
            "biy.",
            "bk.",
            "Bl.",
            "bl.",
            "Bn.",
            "Bnb.",
            "bot.",
            "Böl.",
            "bs.",
            "Bşk.",
            "BUE",
            "Bul.",
            "Bulg.",
            "BÜ",
            "Cad.",
            "CAEC",
            "cal",
            "CAO",
            "CC",
            "CD",
            "CDH",
            "CE",
            "CENTO",
            "CIA",
            "CIF",
            "CIOS",
            "CIP",
            "CIP",
            "cm",
            "CMUK",
            "CNRS",
            "coğ.",
            "COMECON",
            "cos",
            "CSO",
            "Cum. Bşk.",
            "CÜ",
            "ÇAYKUR",
            "çev.",
            "ÇS",
            "ÇUKOBİRLİK",
            "ÇÜ",
            "Çvş.",
            "D",
            "dal",
            "dam",
            "DAP",
            "db.",
            "dbl.",
            "DDT",
            "DDY",
            "DEÜ",
            "dg",
            "DGM",
            "DGS",
            "DHMİ",
            "DİE",
            "dk.",
            "dl",
            "DLH",
            "dm",
            "DMO",
            "DNA",
            "Doç.",
            "doğ.",
            "DPT",
            "Dr.",
            "drl.",
            "DSİ",
            "DSÖ",
            "DT",
            "DTCF",
            "DTÖ",
            "DÜ",
            "Dz. Kuv.",
            "Dz. Kuv. K.",
            "dzl.",
            "e.",
            "EAC",
            "EAT",
            "EBU",
            "Ecz.",
            "ed.",
            "EEG",
            "EFT",
            "EFTA",
            "EGO",
            "EİEİ",
            "EKG",
            "ekon.",
            "EMG",
            "EMK",
            "Ens.",
            "EPA",
            "EPDK",
            "ERDEMİR",
            "Erm.",
            "ESA",
            "ESHOT",
            "ET",
            "EÜ",
            "f.",
            "Fak.",
            "FAO",
            "Far.",
            "FBI",
            "fel.",
            "FIBA",
            "FIDE",
            "FIFA",
            "FILA",
            "FIR",
            "fil.",
            "FİSKOBİRLİK",
            "fiz.",
            "fizy.",
            "FKB",
            "FM",
            "Fr.",
            "FÜ",
            "G",
            "g",
            "GAP",
            "GATA",
            "GAZÜ",
            "GB",
            "GB",
            "GB",
            "GD",
            "Gen.",
            "geom.",
            "gn.",
            "Gnkur.",
            "GOÜ",
            "Gön.",
            "gr.",
            "Grt",
            "GSM",
            "GSMH",
            "GSYH",
            "GÜ",
            "H",
            "HA",
            "HABITAT",
            "HAVAŞ",
            "HDD",
            "hek.",
            "HIV",
            "hl",
            "hlk.",
            "hm",
            "HMUK",
            "HO",
            "Hst.",
            "Hs. Uzm.",
            "huk.",
            "HÜ",
            "Hv. Kuv.",
            "Hv. Kuv. K.",
            "Hz.",
            "Hz.",
            "hzl.",
            "Hz. öz.",
            "IAAF",
            "IAEA",
            "IATA",
            "ICAO",
            "ICJ",
            "ICRC",
            "IDA",
            "IDB",
            "ILO",
            "IMF",
            "INTERPOL",
            "IOC",
            "IPI",
            "IRO",
            "ISBN",
            "ISMN",
            "ISO",
            "ISSN",
            "ITO",
            "İbr.",
            "İETT",
            "İKÖ",
            "İMKB",
            "İng.",
            "is.",
            "İSDEMİR",
            "İSKİ",
            "İSO",
            "İsp.",
            "İŞKUR",
            "işl.",
            "İŞOT",
            "İt.",
            "İTB",
            "İTO",
            "İTÜ",
            "İÜ",
            "İZTB",
            "İZTO",
            "J",
            "JAL",
            "Jap.",
            "jeol.",
            "JGK",
            "KARDEMİR",
            "KB",
            "KBB",
            "KD",
            "KDV",
            "KEİ",
            "kg",
            "KGB",
            "KHK",
            "KİK",
            "kim.",
            "KİT",
            "KKK",
            "KKTC",
            "km",
            "KMS",
            "KOBİ",
            "KOİ",
            "koor.",
            "Kor.",
            "Kora.",
            "Korg.",
            "KOSGEB",
            "KPDS",
            "krş.",
            "KTÜ",
            "Kur.",
            "Kur. Bşk.",
            "KÜ",
            "l",
            "Lat.",
            "LCV",
            "LES",
            "LİBOR",
            "LP",
            "LPG",
            "Ltd.",
            "M",
            "m",
            "Mac.",
            "Mah.",
            "Mah.",
            "man.",
            "mat.",
            "MB",
            "MD.",
            "MEB",
            "mec.",
            "MGK",
            "mim.",
            "min.",
            "MİT",
            "MK",
            "MKE",
            "MKS",
            "MKYK",
            "mm",
            "MOSSAD",
            "MÖ",
            "MPİ",
            "MPM",
            "MS",
            "MSÜ",
            "MTA",
            "MÜ",
            "Müh.",
            "Mür.",
            "müz.",
            "MYK",
            "NASA",
            "NATO",
            "NOTAM",
            "Nö.",
            "Nö. Sb.",
            "Nu.",
            "OAPEC",
            "ODTÜ",
            "OECD",
            "Okt.",
            "Onb.",
            "OPEC",
            "Opr.",
            "Or.",
            "Ora.",
            "Ord.",
            "Org.",
            "Ort.",
            "OSB",
            "Osm. T.",
            "OYAK",
            "ÖİB",
            "öl.",
            "ör.",
            "ÖSS",
            "ÖSYM",
            "ÖTV",
            "ÖYK",
            "ÖYS",
            "öz.",
            "ped.",
            "PEN",
            "PETKİM",
            "PK",
            "PO",
            "POAŞ",
            "Port.",
            "Prof.",
            "psikol.",
            "PTT",
            "RAM",
            "RC",
            "RCD",
            "RNA",
            "ROM",
            "Ro-Ro",
            "RTÜK",
            "Rum.",
            "Rus.",
            "S",
            "s.",
            "sa.",
            "SALT",
            "SAS",
            "SAT",
            "Sb.",
            "SBF",
            "SEK",
            "SEKA",
            "sf.",
            "SHÇEK",
            "SKT",
            "Sl.",
            "Sn.",
            "sn.",
            "snt.",
            "Sok.",
            "sos.",
            "SOS",
            "sp.",
            "SPK",
            "SSCB",
            "SSK",
            "STK",
            "STÖ",
            "SÜ",
            "Ş",
            "Şb.",
            "T.",
            "t",
            "TAEK",
            "TAI",
            "TAO",
            "tar.",
            "TARİŞ",
            "TASS",
            "TAŞ",
            "Tb.",
            "TBB",
            "TBMM",
            "T.C.",
            "TCDD",
            "TCK",
            "TCK",
            "TCMB",
            "TCZB",
            "TDÇİ",
            "TDİ",
            "TDK",
            "TEAŞ",
            "TEDAŞ",
            "TEFE",
            "TEİAŞ",
            "tek.",
            "TEK",
            "telg.",
            "TEM",
            "TETAŞ",
            "TGC",
            "TGS",
            "Tğm.",
            "THA",
            "THK",
            "THK",
            "THY",
            "TIR",
            "tic.",
            "TİGEM",
            "TİKA",
            "TİM",
            "TİSK",
            "tiy.",
            "TKAE",
            "TKB",
            "TKF",
            "TKİ",
            "TL",
            "tel.",
            "tlks.",
            "tls.",
            "TM",
            "TMMOB",
            "TMO",
            "TOBB",
            "TODAİE",
            "TOEFL",
            "TOKİ",
            "Top.",
            "TP",
            "TPAO",
            "TR",
            "TRT",
            "TSE",
            "TSİ",
            "TSK",
            "TT",
            "TTB",
            "TTOK",
            "TTKB",
            "TTK",
            "Tug.",
            "Tuğa.",
            "Tuğg.",
            "TUS",
            "TÜ",
            "TÜBA",
            "TÜBİTAK",
            "TÜFE",
            "Tüm.",
            "Tüma.",
            "Tümg.",
            "TÜPRAŞ",
            "TÜRDOK",
            "TÜRKSAT",
            "TÜRSAB",
            "TÜTAV",
            "TV",
            "TZDK",
            "TZOB",
            "UEFA",
            "UFO",
            "UHF",
            "UK",
            "UN",
            "UNAC",
            "UNESCO",
            "UNICEF",
            "UNO",
            "UPI",
            "UPU",
            "USA",
            "USAŞ",
            "UÜ",
            "Uzm.",
            "Ü",
            "Üçvş.",
            "ÜDS",
            "ÜFE",
            "ünl.",
            "Ütğm.",
            "ÜT",
            "vb.",
            "vd.",
            "VDMK",
            "Vet.",
            "VHF",
            "VIP",
            "vs.",
            "w",
            "WAP",
            "WB",
            "WHO",
            "WTO",
            "Yrd. Doç.",
            "Yay.",
            "Yb.",
            "YDS",
            "Yd. Sb.",
            "YKr",
            "YÖK",
            "YÖS",
            "YSE",
            "YSK",
            "YTL",
            "YTÜ",
            "Yun.",
            "YURTKUR",
            "Y. Mim.",
            "Y. Müh.",
            "yy.",
            "YYÜ",
            "Yzb.",
            "zf.",
            "ZF",
            "zm.",
            "ZMO",
            "zool.",
            "A",
            "B",
            "C",
            "Ç",
            "D",
            "E",
            "F",
            "G",
            "Ğ",
            "H",
            "İ",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "Ö",
            "P",
            "R",
            "S",
            "Ş",
            "T",
            "U",
            "Ü",
            "V",
            "Y",
            "Z",
            "a",
            "b",
            "c",
            "ç",
            "d",
            "e",
            "f",
            "g",
            "ğ",
            "h",
            "i",
            "ı",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "ö",
            "p",
            "r",
            "s",
            "ş",
            "t",
            "u",
            "ü",
            "v",
            "y",
            "z"
        };

        private readonly ITokenizer tokenizer;

        public TokenBasedSentenceSegmenter(ITokenizer tokenizer)
        {
            this.tokenizer = tokenizer;
        }

        private bool IsEosCandidate(string token)
        {
            return EosCandidateTokens.Contains(token);
        }

        public override IEnumerable<int> GetBoundaryIndices(string paragraph)
        {
            IList<string> tokens = tokenizer.Tokenize(paragraph);
            int index = -1;
            var indices = new List<int>();
            for (int i = 0; i < tokens.Count; i++)
            {
                index += tokens[i].Length;
                if (IsEosCandidate(tokens[i]))
                {
                    if (IsEos(tokens, i))
                    {
                        indices.Add(index);
                    }
                }
            }

            return indices;
        }


        private bool IsEos(IList<string> tokens, int i)
        {
            if (i + 1 == tokens.Count) //Is last token?
            {
                return true;
            }

            if (i == 0)
            {
                return false;
            }

            string prev = tokens[i - 1];
            string curr = tokens[i];
            string next = tokens[i + 1];

            if (_abvvs.Contains(prev + curr))
            {
                return false;
            }
            int x;

            if (Int32.TryParse(prev, out x) && curr == ".")
            {
                return false;
            }
            if (prev.Length == 1 && curr == ".") //Kısaltma olma ihtimali yüksek
            {
                return false;
            }
            if (Closing.Contains(next))
            {
                return false;
            }
            if (next == "[")
            {
                return false;
            }
            if (next == ".")
            {
                return false;
            }
            if (curr == "\"" && !EosCandidateTokens.Contains(prev))
            {
                return false;
            }

            if (curr == "\"" && EosCandidateTokens.Contains(prev))
            {
                if (i + 2 < tokens.Count)
                {
                    if (Char.IsLower(tokens[i + 2][0]))
                    {
                        return false;
                    }
                }
            }
            if (prev.RomanNumeralToArabic() > 0)
            {
                return false;
            }

            return true;
        }
    }
}