//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nuve.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nuve.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roots.xlsx.
        /// </summary>
        internal static string ExternalRootsFileName {
            get {
                return ResourceManager.GetString("ExternalRootsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suffixes.xlsx.
        /// </summary>
        internal static string ExternalSuffixFileName {
            get {
                return ResourceManager.GetString("ExternalSuffixFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root_abbrv.txt.
        /// </summary>
        internal static string InternalAbbreviationsPath {
            get {
                return ResourceManager.GetString("InternalAbbreviationsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root_main.txt.
        /// </summary>
        internal static string InternalMainRootsPath {
            get {
                return ResourceManager.GetString("InternalMainRootsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to root_name.txt.
        /// </summary>
        internal static string InternalPersonNamesPath {
            get {
                return ResourceManager.GetString("InternalPersonNamesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suffix.txt.
        /// </summary>
        internal static string InternalSuffixesPath {
            get {
                return ResourceManager.GetString("InternalSuffixesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string langCodeLength {
            get {
                return ResourceManager.GetString("langCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to morphotactics.xml.
        /// </summary>
        internal static string MorphotacticsFileName {
            get {
                return ResourceManager.GetString("MorphotacticsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orthography.xml.
        /// </summary>
        internal static string OrthographyFileName {
            get {
                return ResourceManager.GetString("OrthographyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\..\Nuve\Resources\.
        /// </summary>
        internal static string ResourcesPath {
            get {
                return ResourceManager.GetString("ResourcesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abbrv.
        /// </summary>
        internal static string SheetNameAbbreviations {
            get {
                return ResourceManager.GetString("SheetNameAbbreviations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main.
        /// </summary>
        internal static string SheetNameMainRoots {
            get {
                return ResourceManager.GetString("SheetNameMainRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string SheetNamePersonNames {
            get {
                return ResourceManager.GetString("SheetNamePersonNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suffix.
        /// </summary>
        internal static string SheetNameSuffixes {
            get {
                return ResourceManager.GetString("SheetNameSuffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to probability must be in range [0-1].
        /// </summary>
        internal static string SolutionFrequency_SetProbability_ExceptionMessage {
            get {
                return ResourceManager.GetString("SolutionFrequency_SetProbability_ExceptionMessage", resourceCulture);
            }
        }
    }
}
